name: Build Release App Bundle

on: 
 push:
    branches: [ "master" ]
 pull_request:
    branches: [ "master" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Decode Keystore
        id: decode_keystore
        uses: timheuer/base64-to-file@v1
        with:
          fileName: 'keystore/keystore.jks'
          encodedString: ${{ secrets.KEYSTORE }}
      - uses: actions/checkout@v3
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
           java-version: '11'
           distribution: 'temurin'
           cache: gradle
           
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: build prod
        run: ./gradlew assembleInternalBetaRelease
      - name: Sign APK
        id: sign_apk
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: app/build/outputs/bundle/internalBetaRelease/*.aab
          signingKeyBase64: ${{ secrets.KEYSTORE }}
          alias: ${{secrets.SIGNING_KEY_ALIAS }}
          keyStorePassword: ${{ secrets.SIGNING_STORE_PASSWORD }}
          keyPassword: ${{  secrets.SIGNING_KEY_PASSWORD }}
          
      - name: Upload release Apk
        uses: actions/upload-artifact@v3.1.0
        with:
          name: app-release
          path: ${{steps.sign_app.outputs.signedReleaseFile}}
          if-no-files-found: error
